# Use RC clock for now
CFLAGS += -DNRF_SDH_CLOCK_LF_SRC=0
CFLAGS += -DNRF_SDH_CLOCK_LF_RC_CTIV=16
CFLAGS += -DNRF_SDH_CLOCK_LF_RC_TEMP_CTIV=4
CFLAGS += -DNRF_SDH_CLOCK_LF_ACCURACY=NRF_CLOCK_LF_ACCURACY_500_PPM
CFLAGS += -DNRF_BL_DFU_ENTER_METHOD_BUTTON_PIN=35

UART_LOG = 0
PROG_HW = stlink
