#!/usr/bin/env python3
#====================================================================================
# Nordic Uart Service client using external module with ble_tool
#
# This file is part of easy_nrf52
# License: LGPL 2.1
# General and full license information is available at:
#    https://github.com/plerup/easy_nrf52
#
# Copyright (c) 2023 Peter Lerup. All rights reserved.
#
#====================================================================================

from ext_ble_tool import init, in_waiting, send_string, read_string, run
import sys, select
import argparse, time


def input_avail():
    return (select.select([sys.stdin], [], [], 0.1))[0]


def nus_client():
    send_string(f"connect;{args.mac};{args.long_range}", "#CONNECTED", int(args.timeout))
    print("Connected")

    input = ""
    while True:
        if input_avail():
            input = sys.stdin.readline()
            if not len(input):
                raise EOFError
            input = input.rstrip()
            if len(input):
                send_string(f"nusc;" + input)
            else:
                print("* Enter a non empty command string")
        elif in_waiting():
            while in_waiting():
                resp = read_string()
                if "#NUSC" in resp:
                    print(resp[6:])
        else:
            time.sleep(0.1)


parser = argparse.ArgumentParser(description='Nus client')
parser.add_argument('-b', dest='mac', required=True,
                    help='Nus server mac address')
parser.add_argument('-t', dest='timeout', default=25,
                    help='Connect timeout in seconds')

args = init(parser)
if args:
    run(nus_client)
