#!/usr/bin/env python3
#====================================================================================
# Nordic Uart Service client
#
# This file is part of easy_nrf52
# License: LGPL 2.1
# General and full license information is available at:
#    https://github.com/plerup/easy_nrf52
#
# Copyright (c) 2025 Peter Lerup. All rights reserved.
#
#====================================================================================
#

import asyncio
import sys, subprocess
import argparse
from itertools import count, takewhile
from typing import Iterator
from binascii import hexlify
from bleak import BleakClient
from bleak.exc import BleakDeviceNotFoundError
from bleak.backends.characteristic import BleakGATTCharacteristic
from aioconsole import ainput


UART_SERVICE_UUID = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
UART_RX_CHAR_UUID = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
UART_TX_CHAR_UUID = "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"

out_file = None

def sliced(data: bytes, n: int) -> Iterator[bytes]:
    return takewhile(len, (data[i : i + n] for i in count(0, n)))

#--------------------------------------------------------------------

def err(str):
    print("* " + str, file=sys.stderr)

#--------------------------------------------------------------------

def fatal(str):
    err(str)
    sys.exit(1)

#--------------------------------------------------------------------

async def uart_terminal(args):

    rx_event = asyncio.Event()

    def info(str):
        if not args.quiet:
            print("- " + str)

    #------------------------

    def handle_disconnect(_: BleakClient):
        info("Disconnected")
        for task in asyncio.all_tasks():
            task.cancel()

    #------------------------

    def hex_data(data):
        return hexlify(data).decode().upper()

    #------------------------

    def handle_rx(_: BleakGATTCharacteristic, data: bytearray):
        output = ""
        if args.hex_format:
            output = hex_data(data)
        else:
            try:
                output = data.decode().rstrip().rstrip('\x00')
            except UnicodeDecodeError:
                output = hex_data(data)
        print(output, flush=True)
        if out_file:
            out_file.write(output + "\n")
        rx_event.set()

    #------------------------

    info(f"Connecting to: {args.mac_addr}...")
    async with BleakClient(args.mac_addr, disconnected_callback=handle_disconnect, timeout=int(args.timeout)) as client:
        await client.start_notify(UART_TX_CHAR_UUID, handle_rx)
        nus = client.services.get_service(UART_SERVICE_UUID)
        assert nus is not None, "UART service not found"
        rx_char = nus.get_characteristic(UART_RX_CHAR_UUID)
        assert rx_char is not None, "UART RX characteristic not found"
        # Make sure we get large MTU in Bluez, fails sometimes for some reason
        if client._backend.__class__.__name__ == "BleakClientBlueZDBus":
            await client._backend._acquire_mtu()
            if rx_char.max_write_without_response_size < 21:
                print("* Failed to increase MTU")

            #assert rx_char.max_write_without_response_size > 21, "Failed to increase MTU"
        if args.string:
            for s in args.string.split(';'):
                rx_event.clear()
                await client.write_gatt_char(rx_char, s.encode("utf-8"), response=True)
                try:
                    await asyncio.wait_for(rx_event.wait(), timeout=args.timeout)
                except asyncio.TimeoutError:
                    pass
        else:
            mess = "Enter command or ctrl-c to exit"
            info(f"Connected (MTU={rx_char.max_write_without_response_size}). {mess}")
            while True:
                try:
                    data = await ainput()
                except (EOFError, KeyboardInterrupt):
                    info("Exit...")
                    break
                if not data:
                    info(mess)
                else:
                    if args.conv_cmd:
                        data = subprocess.run(f"{args.conv_cmd} {data} {args.mac_addr}", stdout=subprocess.PIPE, shell=True).stdout.decode("utf-8").strip()
                    if out_file:
                        out_file.write(data + "\n")
                    for s in sliced(data.encode("utf-8"), rx_char.max_write_without_response_size):
                        await client.write_gatt_char(rx_char, s, response=False)

#--------------------------------------------------------------------

parser = argparse.ArgumentParser(description='Nordic Uart Service (NUS) client')
parser.add_argument('-b', dest='mac_addr', required=True,
                    help='Server mac address')
parser.add_argument('-s', dest='string',
                    help='Send string to server and exit. Separate multiple strings with ;')
parser.add_argument('-x', dest='hex_format', action='store_true',
                    help='Output in hex format')
parser.add_argument('-t', dest='timeout',
                    default=30,
                    help='Connect timeout in seconds. Default 30')
parser.add_argument('-o', dest='out_file',
                    default=None,
                    help='Write output to file as well')
parser.add_argument('-q', dest='quiet', action='store_true',
                    help='Quiet mode')
parser.add_argument('-c', dest='conv_cmd',
                    default=None,
                    help='Convert input with command')

args = parser.parse_args()

out_file = None
if args.out_file:
    try:
        out_file = open(args.out_file, "w")
    except:
        fatal(f"Failed to open: {args.out_file}")


try:
    asyncio.run(uart_terminal(args))
except BleakDeviceNotFoundError:
    fatal("Device not found")
except  KeyboardInterrupt:
    pass
except asyncio.CancelledError:
    pass
