#!/usr/bin/env perl
#====================================================================================
# Find possible enabled and added #define in multiple
# Nordic sdk configuration files
#
# This file is part of easy_nrf52
# License: LGPL 2.1
# General and full license information is available at:
#    https://github.com/plerup/easy_nrf52
#
# Copyright (c) 2022-2024 Peter Lerup. All rights reserved.
#
#====================================================================================

use strict;

my %defines;
my $cnt = 0;
my $diff;
my $f;
foreach my $config (@ARGV) {
  open($f, $config) || die "Failed to open the config file at: $config\n";
  while (<$f>) {
    next unless /^#define\s+(\S+)\s+(\S+)/;
    my ($id, $val) = ($1, $2);
    $diff .= "#ifndef $id\n${_}#endif\n" if (defined($defines{$id}) && $defines{$id} ne $val && $val ne "0") || ($cnt && !defined($defines{$id}));
    $defines{$id} ||= $val;
  }
  close($f);
  $cnt++;
}

print "//\n// SDK config generated by merge_config\n//\n";
print "#include \"nordic_common.h\"\n";
print "#ifdef APP_SDK_CONFIG\n  #include STRINGIFY(APP_SDK_CONFIG)\n#endif\n";
print "#ifndef NRF_SDH_BLE_TOTAL_LINK_COUNT\n#define NRF_SDH_BLE_TOTAL_LINK_COUNT NRF_SDH_BLE_PERIPHERAL_LINK_COUNT+NRF_SDH_BLE_CENTRAL_LINK_COUNT\n#endif\n";
print $diff;
open($f, $ARGV[0]);
while (<$f>) {
  print $_;
}
close($f);
